[package]
name = "rust_patch_client"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = { version = "0.11.18", features = ["blocking", "json"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.104"
log = "0.4.19"
simplelog = "0.12.0"
anyhow = "1.0.64"
sysinfo = "0.37.2"
lazy_static = "1.4.0"
termcolor = "1.4.1"
env_logger = "0.10.0"
local-ip-address = "0.6.5"
chrono = "0.4"

# Optional Windows service support
windows-service = { version = "0.8.0", optional = true }

# Add windows crate for Windows API calls
windows = { version = "0.48.0", optional = true }

[features]
default = []
windows = ["windows-service", "windows"]

[[bin]]
name = "rust_patch_client"
path = "src/main.rs"

[[bin]]
name = "patchpilot_updater"
path = "src/patchpilot_updater.rs"
